# ARITHMETIC operators (+,-,*,/,//,%,**)
# operator precedence - Parentheses , Exponentiation , 

print('adddition', 2+3)
print('subtraction', 9-3)
print('multiplication', 3*8)
print('division', 7/3)

print('floor division', 7//3)

print('modulus', 7%3)

print('exponential', 6**2)
 
# relational(> ,< ,>=, <=, ==, !=)
# output in this case is always a boolean value

# logical operators (and, or, not)

print(True and True)
print(True and False)
print(False and True)
print(False and False)

print(True or True)
print(True or False)
print(False or True)
print(False or False)


print(not True) # we can use with or without brackets.
print(not False)