print("hello, type in ur name:")
n=str(input())
print("which place are u in?")
p=str(input())
print("hello",n,"how is the weather in",p,"?")
w=str(input())
print("what is ur age?")
age=int(input())
print("good to know u r",age,"years old")